package root;
import java.awt.event.KeyEvent;
/*
 * MathDialog.java
 *
 * Created on 3 janvier 2003, 14:34
 * the code source is distributed under the GPL.
 * Please see http://www.fsf.org/copyleft/gpl.html 
 */

/**
 *
 * @author  Patrice Maupou
 */
public class MathDialog extends java.awt.Dialog {
  
  /** Creates new form MathDialog
     * @param parent */
  public MathDialog(java.awt.Frame parent) {
    super(parent);
    initComponents();
  }
  
  public MathDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    ErrorText = new java.awt.Label();
    panelButtons = new java.awt.Panel();
    oui = new java.awt.Button();
    non = new java.awt.Button();

    setBackground(new java.awt.Color(204, 204, 204));
    setFont(new java.awt.Font("Dialog", 0, 11));
    setForeground(java.awt.Color.black);
    setModal(true);
    setResizable(false);
    setTitle("Erreur");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    ErrorText.setAlignment(java.awt.Label.CENTER);
    ErrorText.setFont(new java.awt.Font("Dialog", 0, 11));
    add(ErrorText, java.awt.BorderLayout.CENTER);

    oui.setLabel("oui");
    oui.setVisible(false);
    oui.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        ouiKeyPressed(evt);
      }
    });
    oui.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ouiActionPerformed(evt);
      }
    });

    panelButtons.add(oui);

    non.setLabel("non");
    non.setVisible(false);
    non.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        nonKeyPressed(evt);
      }
    });
    non.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nonActionPerformed(evt);
      }
    });

    panelButtons.add(non);

    add(panelButtons, java.awt.BorderLayout.SOUTH);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-200)/2, (screenSize.height-100)/2, 200, 100);
  }// </editor-fold>//GEN-END:initComponents

  private void nonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nonKeyPressed
    switch (evt.getKeyCode()) {
      case KeyEvent.VK_ENTER :
        buttonActionPerformed(false);
        break;
      case KeyEvent.VK_LEFT :
        oui.requestFocus();
    }
  }//GEN-LAST:event_nonKeyPressed

  private void ouiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ouiKeyPressed
    switch (evt.getKeyCode()) {
      case KeyEvent.VK_ENTER :
        buttonActionPerformed(true);
        break;
      case KeyEvent.VK_RIGHT :
       non.requestFocus();
    }
  }//GEN-LAST:event_ouiKeyPressed

  private void nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonActionPerformed
    buttonActionPerformed(false);
  }//GEN-LAST:event_nonActionPerformed

  private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
    buttonActionPerformed(true);
  }//GEN-LAST:event_ouiActionPerformed

  private void buttonActionPerformed(boolean accept) {
    setAnswer(accept);                  
    setVisible(false);
    setButtonsVisible(false);
    dispose();
  }
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new MathDialog(new java.awt.Frame(), true).setVisible(true);
  }
  
  public void setLabel(String s) {
    ErrorText.setText(s);
  }
  
  public boolean isAnswer() {
    return answer;
  }

  private void setAnswer(boolean answer) {
    this.answer = answer;
  }
  
  public void setButtonsVisible(boolean buttons) {
    oui.setVisible(buttons);
    non.setVisible(buttons);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Label ErrorText;
  private java.awt.Button non;
  private java.awt.Button oui;
  private java.awt.Panel panelButtons;
  // End of variables declaration//GEN-END:variables
  private boolean answer;

}
